INSERT INTO FILMSKATRAKAARHIVA (
    BARKOD, ORIGINALNINASLOV, JEZIKORIGINALA, TON, PORIJEKLO_ZEMLJAPROIZVODNJE, GODINAPROIZVODNJE, MARKIN, MARKOUT, DURATION, BROJMEDIJA, EMISIJA, LICENCA, RADNINASLOV
)

VALUES (
           'B-208396', 'Restoran Gladni student', 'Hrvatski', 'Nema', 'Hrvatska', 2023, '00:00:00', '00:02:12', '00:02:12', '1000', 'NULL', 'NULL', 'NULL'
       );



INSERT INTO FILMSKATRAKAARHIVA (
    BARKOD, ORIGINALNINASLOV, JEZIKORIGINALA, TON, PORIJEKLO_ZEMLJAPROIZVODNJE, GODINAPROIZVODNJE, MARKIN, MARKOUT, DURATION, BROJMEDIJA
)
VALUES (
           'B-208397', 'Ema se vraća u Superstar', 'Hrvatski', 'Stereo', 'Hrvatska', 2024, '00:00:00', '00:33:10', '00:33:10', '10002'
       );



INSERT INTO FILMSKATRAKAARHIVA (
    BARKOD, ORIGINALNINASLOV, JEZIKORIGINALA, TON, PORIJEKLO_ZEMLJAPROIZVODNJE, GODINAPROIZVODNJE, MARKIN, MARKOUT, DURATION, BROJMEDIJA, LICENCA
)
VALUES (
           'IMX-035010', 'Jaškovo - Dvorac', 'Hrvatski', 'Mono, sep.mag.', 'Hrvatska', 1989, '00:00:00', '00:12:15', '00:12:15', '1900', 'CC BY'
       );



INSERT INTO FILMSKATRAKAARHIVA (
    BARKOD, ORIGINALNINASLOV, JEZIKORIGINALA, TON, PORIJEKLO_ZEMLJAPROIZVODNJE, GODINAPROIZVODNJE, MARKIN, MARKOUT, DURATION, BROJMEDIJA, LICENCA
)
VALUES (
           'IMX-035011', 'VOLONTERI', 'Hrvatski', 'Nema', 'Hrvatska', 1961, '00:00:00', '00:01:45', '00:01:45', '2011', 'CC BY-ND'
       );



INSERT INTO FILMSKATRAKAARHIVA (
    BARKOD, ORIGINALNINASLOV, JEZIKORIGINALA, TON, PORIJEKLO_ZEMLJAPROIZVODNJE, GODINAPROIZVODNJE, MARKIN, MARKOUT, DURATION, BROJMEDIJA, LICENCA
)
VALUES (
           'IMX-035012', 'Krapina - Panorama mjesta', 'Hrvatski', 'Mono, sep.mag.', 'Hrvatska', 1997, '00:00:00', '00:09:15', '00:09:15', '29001', 'CC BY-ND'
       );



INSERT INTO FILMSKATRAKAARHIVA (
    BARKOD, ORIGINALNINASLOV, JEZIKORIGINALA, TON, PORIJEKLO_ZEMLJAPROIZVODNJE, GODINAPROIZVODNJE, MARKIN, MARKOUT, DURATION, BROJMEDIJA, LICENCA
)
VALUES (
           'IMX-035013', 'Meksički grah', 'Španjolski', 'Stereo, optički', 'Meksiko', 2004, '00:00:00', '00:01:52', '00:01:52', '3031', 'CC BY'
       );



INSERT INTO FILMSKATRAKAARHIVA (
    BARKOD, ORIGINALNINASLOV, JEZIKORIGINALA, TON, PORIJEKLO_ZEMLJAPROIZVODNJE, GODINAPROIZVODNJE, MARKIN, MARKOUT, DURATION, BROJMEDIJA
)
VALUES (
           'B-208398', 'Stubište usred šume', 'Slovenski', 'Mono', 'Slovenija', 1972, '00:00:00', '00:03:10', '00:03:10', '110'
       );



INSERT INTO FILMSKATRAKAARHIVA (
    BARKOD, ORIGINALNINASLOV, JEZIKORIGINALA, TON, PORIJEKLO_ZEMLJAPROIZVODNJE, GODINAPROIZVODNJE, MARKIN, MARKOUT, DURATION, BROJMEDIJA
)
VALUES (
           'B-208399', 'America''s Most Wanted', 'Engleski', 'Stereo, optički', 'Velika Britanija', 2001, '00:00:00', '00:21:10', '00:21:10', '21012'
       );



INSERT INTO FILMSKATRAKAARHIVA (
    BARKOD, ORIGINALNINASLOV, JEZIKORIGINALA, TON, PORIJEKLO_ZEMLJAPROIZVODNJE, GODINAPROIZVODNJE, MARKIN, MARKOUT, DURATION, BROJMEDIJA
)
VALUES (
           'B-208400', '33. Dani hrvatskog filma', 'Hrvatski', 'Stereo, optički', 'Hrvatska', 2014, '00:00:00', '00:02:10', '00:02:10', '21013'
       );



INSERT INTO FILMSKATRAKAARHIVA (
    BARKOD, ORIGINALNINASLOV, JEZIKORIGINALA, TON, PORIJEKLO_ZEMLJAPROIZVODNJE, GODINAPROIZVODNJE, MARKIN, MARKOUT, DURATION, BROJMEDIJA
)
VALUES (
           'B-208401', 'Otvorenje hotela Vis', 'Hrvatski', 'Mono, optički', 'Hrvatska', 1984, '00:00:00', '00:02:10', '00:02:10', '21013'
       );



INSERT INTO FILMSKATRAKAARHIVA (
    BARKOD, ORIGINALNINASLOV, JEZIKORIGINALA, TON, PORIJEKLO_ZEMLJAPROIZVODNJE, GODINAPROIZVODNJE, MARKIN, MARKOUT, DURATION, BROJMEDIJA, LICENCA
)
VALUES (
           'B-208402', 'Zbirka Emila Laszowskog', 'Hrvatski', 'Mono, sep.mag.', 'Hrvatska', 1963, '00:00:00', '00:20:15', '00:20:15', '1013', 'CC BY-ND'
       );



INSERT INTO FILMSKATRAKAARHIVA (
    BARKOD, ORIGINALNINASLOV, JEZIKORIGINALA, TON, PORIJEKLO_ZEMLJAPROIZVODNJE, GODINAPROIZVODNJE, MARKIN, MARKOUT, DURATION, BROJMEDIJA, LICENCA
)
VALUES (
           'IMX-035009', 'Zbirka uskrsnih jaja', 'Hrvatski', 'Mono, sep.mag.', 'Hrvatska', 1963, '00:08:00', '00:12:15', '00:20:15', 'Z-7462', 'CC BY'
       );

INSERT INTO FILMSKATRAKAARHIVA (
    BARKOD, ORIGINALNINASLOV, JEZIKORIGINALA, TON, PORIJEKLO_ZEMLJAPROIZVODNJE, GODINAPROIZVODNJE, MARKIN, MARKOUT, DURATION, BROJMEDIJA, EMISIJA, LICENCA, RADNINASLOV
)

VALUES (
           'B-208396', 'Restoran Gladni student', 'Hrvatski', 'Nema', 'Hrvatska', 2023, '00:00:00', '00:02:12', '00:02:12', '1000', 'NULL', 'NULL', 'NULL'
       );



INSERT INTO FILMSKATRAKAARHIVA (
    BARKOD, ORIGINALNINASLOV, JEZIKORIGINALA, TON, PORIJEKLO_ZEMLJAPROIZVODNJE, GODINAPROIZVODNJE, MARKIN, MARKOUT, DURATION, BROJMEDIJA
)
VALUES (
           'B-208397', 'Ema se vraća u Superstar', 'Hrvatski', 'Stereo', 'Hrvatska', 2024, '00:00:00', '00:33:10', '00:33:10', '10002'
       );



INSERT INTO FILMSKATRAKAARHIVA (
    BARKOD, ORIGINALNINASLOV, JEZIKORIGINALA, TON, PORIJEKLO_ZEMLJAPROIZVODNJE, GODINAPROIZVODNJE, MARKIN, MARKOUT, DURATION, BROJMEDIJA, LICENCA
)
VALUES (
           'IMX-035010', 'Jaškovo - Dvorac', 'Hrvatski', 'Mono, sep.mag.', 'Hrvatska', 1989, '00:00:00', '00:12:15', '00:12:15', '1900', 'CC BY'
       );



INSERT INTO FILMSKATRAKAARHIVA (
    BARKOD, ORIGINALNINASLOV, JEZIKORIGINALA, TON, PORIJEKLO_ZEMLJAPROIZVODNJE, GODINAPROIZVODNJE, MARKIN, MARKOUT, DURATION, BROJMEDIJA, LICENCA
)
VALUES (
           'IMX-035011', 'VOLONTERI', 'Hrvatski', 'Nema', 'Hrvatska', 1961, '00:00:00', '00:01:45', '00:01:45', '2011', 'CC BY-ND'
       );



INSERT INTO FILMSKATRAKAARHIVA (
    BARKOD, ORIGINALNINASLOV, JEZIKORIGINALA, TON, PORIJEKLO_ZEMLJAPROIZVODNJE, GODINAPROIZVODNJE, MARKIN, MARKOUT, DURATION, BROJMEDIJA, LICENCA
)
VALUES (
           'IMX-035012', 'Krapina - Panorama mjesta', 'Hrvatski', 'Mono, sep.mag.', 'Hrvatska', 1997, '00:00:00', '00:09:15', '00:09:15', '29001', 'CC BY-ND'
       );



INSERT INTO FILMSKATRAKAARHIVA (
    BARKOD, ORIGINALNINASLOV, JEZIKORIGINALA, TON, PORIJEKLO_ZEMLJAPROIZVODNJE, GODINAPROIZVODNJE, MARKIN, MARKOUT, DURATION, BROJMEDIJA, LICENCA
)
VALUES (
           'IMX-035013', 'Meksički grah', 'Španjolski', 'Stereo, optički', 'Meksiko', 2004, '00:00:00', '00:01:52', '00:01:52', '3031', 'CC BY'
       );



INSERT INTO FILMSKATRAKAARHIVA (
    BARKOD, ORIGINALNINASLOV, JEZIKORIGINALA, TON, PORIJEKLO_ZEMLJAPROIZVODNJE, GODINAPROIZVODNJE, MARKIN, MARKOUT, DURATION, BROJMEDIJA
)
VALUES (
           'B-208398', 'Stubište usred šume', 'Slovenski', 'Mono', 'Slovenija', 1972, '00:00:00', '00:03:10', '00:03:10', '110'
       );



INSERT INTO FILMSKATRAKAARHIVA (
    BARKOD, ORIGINALNINASLOV, JEZIKORIGINALA, TON, PORIJEKLO_ZEMLJAPROIZVODNJE, GODINAPROIZVODNJE, MARKIN, MARKOUT, DURATION, BROJMEDIJA
)
VALUES (
           'B-208399', 'America''s Most Wanted', 'Engleski', 'Stereo, optički', 'Velika Britanija', 2001, '00:00:00', '00:21:10', '00:21:10', '21012'
       );



INSERT INTO FILMSKATRAKAARHIVA (
    BARKOD, ORIGINALNINASLOV, JEZIKORIGINALA, TON, PORIJEKLO_ZEMLJAPROIZVODNJE, GODINAPROIZVODNJE, MARKIN, MARKOUT, DURATION, BROJMEDIJA
)
VALUES (
           'B-208400', '33. Dani hrvatskog filma', 'Hrvatski', 'Stereo, optički', 'Hrvatska', 2014, '00:00:00', '00:02:10', '00:02:10', '21013'
       );



INSERT INTO FILMSKATRAKAARHIVA (
    BARKOD, ORIGINALNINASLOV, JEZIKORIGINALA, TON, PORIJEKLO_ZEMLJAPROIZVODNJE, GODINAPROIZVODNJE, MARKIN, MARKOUT, DURATION, BROJMEDIJA
)
VALUES (
           'B-208401', 'Otvorenje hotela Vis', 'Hrvatski', 'Mono, optički', 'Hrvatska', 1984, '00:00:00', '00:02:10', '00:02:10', '21013'
       );



INSERT INTO FILMSKATRAKAARHIVA (
    BARKOD, ORIGINALNINASLOV, JEZIKORIGINALA, TON, PORIJEKLO_ZEMLJAPROIZVODNJE, GODINAPROIZVODNJE, MARKIN, MARKOUT, DURATION, BROJMEDIJA, LICENCA
)
VALUES (
           'B-208402', 'Zbirka Emila Laszowskog', 'Hrvatski', 'Mono, sep.mag.', 'Hrvatska', 1963, '00:00:00', '00:20:15', '00:20:15', '1013', 'CC BY-ND'
       );



INSERT INTO FILMSKATRAKAARHIVA (
    BARKOD, ORIGINALNINASLOV, JEZIKORIGINALA, TON, PORIJEKLO_ZEMLJAPROIZVODNJE, GODINAPROIZVODNJE, MARKIN, MARKOUT, DURATION, BROJMEDIJA, LICENCA
)
VALUES (
           'IMX-035009', 'Zbirka uskrsnih jaja', 'Hrvatski', 'Mono, sep.mag.', 'Hrvatska', 1963, '00:08:00', '00:12:15', '00:20:15', 'Z-7462', 'CC BY'
       );

